### ISSUE TITLE
A css file is missing: dollie/core/Extras/advanced-forms/assets/dist/css/form.css

### ISSUE THREAD

**Issue by cmhello** [DollieWP/dollie#1]
Failed to load resource: the server responded with a status of 404 :

/dollie/core/Extras/advanced-forms/assets/dist/css/form.css

**Comment by cmhello** [comment]
Also missing: dollie/core/Extras/advanced-forms/assets/dist/js/forms.js

**Comment by cmhello** [comment]
The correct path should be:
/dollie/core/Extras/advanced-forms/assets/css/form.css
/dollie/core/Extras/advanced-forms/assets/js/forms.js

**Comment by codezz** [comment]
Hi, please update dollie plugin to latest version and that issue should already be fixed. Let me know
